services:
  web:
    ports:
      - 80:80
    hostname: php-apache
    build: ./php-apache
    restart: always
  mariadb:
    hostname: mariadb
    build: ./mariadb
    restart: always
  clicker-js:
    build: ./js-clicker
    restart: always
